apiVersion: v1
kind: Service
metadata:
  name: maple-organization-postgres-service
  namespace: maple-system
spec:
  type: ClusterIP
  ports:
    - port: 5402
      targetPort: 5432
  selector:
    app: maple-organization-postgres
